[package]
name = "xv6-rust"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "kernel"
path = "src/kernel.rs"

[profile.dev]
panic = "abort"
opt-level = 0

[profile.release]
panic = "abort"
opt-level = "z"

[dependencies]
volatile = "0.2.6"